[package]
name = "heimdall-ebpf"
version = "0.1.4"
edition = "2024"
license = "MIT"
publish = false

[dependencies]
aya-ebpf = "0.1"
heimdall-common = { version = "0.1.4", path = "../heimdall-common", default-features = false }

[[bin]]
name = "heimdall-ebpf"
path = "src/main.rs"

[workspace]

[profile.release]
opt-level = 2
lto = false
